### ISSUE TITLE
complete descr length: 

### ISSUE THREAD

**Issue by lalalagartija** [dacase/rnamotif#4]
Hi, 

rnamotif works but I always get a warning

"complete descr length: min/max = 20/70"

Here is my description file : 
`descr
   h5( minlen=10, mispair=2 , tag='h1', chk_both_strs = 0) ss (minlen=0, maxlen=10) h3(tag='h1')

score
    {
   SCORE =  length( h5['h1']) -  mispairs(h5['h1']);
   if( SCORE >= 11 ){
     ACCEPT ;
     } else {
     REJECT ;
     }
   }`

Is there something wrong with the file ? 
Thanks !

**Comment by tjmacke** [comment]
It's not a warning. It's just an informational message that tells you the min and max lengths of any solution. The original users (Isis Pharm, now Ionis Pharm) wanted to have a report of the min and max lengths of the possible solutions. This is b/c many parts of a descriptor may have variable lengths, but element matching is done independently for each element, the idea being any non-helical element length dependencies would be handled in the score section. Another use was finding unintentionally unbounded elements.  Say your ss() element above was ss(seq="^ggaa").  This is an unbounded element, which while syntactically correct might not have been what you wanted. And if that element was nested 2 or 3 level deep it would be easy to overlook.
The message is printed in the if block starting at rnamot.c:85.
Tom    On Saturday, June 22, 2024 at 09:44:00 AM PDT, David A Case ***@***.***> wrote:  
 
 

On Fri, Jun 21, 2024, lalalagartija wrote:
>
>rnamotif works but I always get a warning
>
>"complete descr length: min/max = 20/70"
>
>Here is my description file :
>`descr
> h5( minlen=10, mispair=2 , tag='h1', chk_both_strs = 0) ss (minlen=0, maxlen=10) h3(tag='h1')
>
>score
> {
> SCORE = length( h5['h1']) - mispairs(h5['h1']);
> if( SCORE >= 11 ){
> ACCEPT ;
> } else {
> REJECT ;
> }
> }`
>
>Is there something wrong with the file ?

Try adding explicit minimum and maximum lengths to h3. Does your file do
what you expect? It looks like the warning is just stating that you are
using the defaults, which may be OK if they are what you want.

cc-ing to Tom Macke, who wrote this code

...dac

**Comment by lalalagartija** [comment]
I understand ! Thank you very much. This message is helpful indeed. 
And adding sizes to the h3 elements did not change the message.
